ALTER TABLE "diagrams"
  ADD COLUMN IF NOT EXISTS "includedElementIds" JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "schemaVersion" INTEGER NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS "migrationWarnings" JSONB NOT NULL DEFAULT '[]';
